---
title: "Add covariates: example on RTP area"
output: html_document
date: "2023-11-09"
---

Load tools

```{r, message=F}
if (!require(pacman)){
    install.packages('pacman')
    library(pacman)
}
p_load(terra, tidyterra, exactextractr, sf, dplyr, fastDummies, 
       viridis, ggplot2)
source("../R/add_covariates.R")
```


```{r}
nc <- vect(paste0("../input/NC_county_boundary/",
                  "North_Carolina_State_and_County_Boundary_Polygons.shp"))
same.crs(crs(nc), "EPSG:6543")
```

## Create prediction grid based on imperviousness aggregation

```{r}
imp <- rast("../input/NC_imperviousness_2019.tif")
nc_proj <- terra::project(nc, crs(imp))
imp <- terra::mask(imp, nc_proj)
 # aggregation at 300m
pred_rast <- aggregate(imp, fact = 10, fun = "mean")
names(pred_rast) <- "imp"
plot(pred_rast)
```
## Zoom om RTP area

```{r}
lat <- c(35.6, 36.11, 36.11, 35.6)
lon <- c(-79.19, -79.19, -78.39, -78.39)
ext_rtp <- vect(cbind(lon, lat), type = "polygons", crs="EPSG:4326")
ext_rtp <- terra::project(ext_rtp, crs(pred_rast))
pred_rast_rtp <- terra::crop(pred_rast, ext_rtp)
#plot(pred_rast_rtp)
pred_vect_rtp <- terra::as.points(pred_rast_rtp)
```


## Add spatial covariates

Tree canopy height

```{r}
pred_vect_rtp <- add_canopy_h(sp_vect = pred_vect_rtp)
#plot(x = pred_vect_rtp, y = "canopy_h", cex = 0.2)
```
Digital elevation model 

```{r}
pred_vect_rtp <- add_dem(sp_vect = pred_vect_rtp)
#plot(x = pred_vect_rtp, y = "dem", cex = 0.2)
```

Tree canopy cover 

```{r}
pred_vect_rtp <- add_tcc(sp_vect = pred_vect_rtp)
#plot(x = pred_vect_rtp, y = "tcc", cex = 0.2)
```

Building footprint

```{r}
pred_vect_rtp <- add_build_fp(sp_vect = pred_vect_rtp)
#plot(x = pred_vect_rtp, y = "build_fp", cex = 0.2)
```

Building height

```{r}
pred_vect_rtp <- add_build_h(sp_vect = pred_vect_rtp)
#plot(x = pred_vect_rtp, y = "build_h", cex = 0.2)
```

Land cover ratio
 
```{r}
lc <- rast("../input/NC_nlcd_crs-wgs84.tif")
pred_vect_rtp <- add_nlcd_class_ratio(pred_vect_rtp, nlcd = lc)
```


```{r}
pred_rast_rtp <- terra::rasterize(pred_vect_rtp, 
                         pred_rast_rtp, 
                         field = names(pred_vect_rtp))
head(pred_rast_rtp)
plot(pred_rast_rtp[[1:6]])
plot(pred_rast_rtp[[7:21]])
```

Add terrain covariates to raster

```{r}
pred_rast_rtp <- add_terrain(pred_rast_rtp)
plot(pred_rast_rtp[[22:25]])
```
