---
title: "Create testdata"
output: html_document
date: "2023-12-07"
---

Load covariate file names

```{r}
files <- list_covar_nc(covar_folder = "../input/")
```

Extract RTP covariates 

```{r}
rtp_subset <- function(sp) {
  lat <- c(35.6, 36.11, 36.11, 35.6)
  lon <- c(-79.19, -79.19, -78.39, -78.39)
  ext <- terra::vect(cbind(lon, lat),
                     type = "polygons",
                     crs = "EPSG:4326")
  ext_proj <- terra::project(ext, terra::crs(sp))
  crop_sp <- terra::crop(sp, ext_proj)
  return(crop_sp)
}
```

```{r}
imp <- terra::rast(files$imp)
imp_rtp <- rtp_subset(imp)
terra::writeRaster(imp_rtp, "../tests/testdata/rtp_imp.tif", overwrite = TRUE)

tcc <- terra::rast(files$tcc)
tcc_rtp <- rtp_subset(tcc)
terra::writeRaster(tcc_rtp, "../tests/testdata/rtp_tcc.tif", overwrite = TRUE)

build_fp <- terra::rast(files$build_fp)
build_fp_rtp <- rtp_subset(build_fp)
terra::writeRaster(build_fp_rtp, "../tests/testdata/rtp_build_fp.tif",
                   overwrite = TRUE)

dem <- terra::rast(files$dem)
dem_rtp <- rtp_subset(dem) %>%
  terra::aggregate(fact = 100)
terra::writeRaster(dem_rtp, "../tests/testdata/rtp_dem.tif", overwrite = TRUE)

canopy_h <- terra::rast(files$canopy_h)
canopy_h_rtp <- rtp_subset(canopy_h) %>%
  terra::aggregate(fact = 100)
terra::writeRaster(canopy_h_rtp, "../tests/testdata/rtp_canopy_h.tif",
                   overwrite = TRUE)

build_h <- terra::vect(files$build_h)
build_h_rtp <- rtp_subset(build_h)
terra::writeVector(build_h_rtp, "../tests/testdata/rtp_build_h.shp",
                   overwrite = TRUE)

nlcd <- terra::rast(files$nlcd)
nlcd_rtp <- rtp_subset(nlcd)
terra::writeRaster(nlcd_rtp, "../tests/testdata/rtp_nlcd.tif", overwrite = TRUE)

nc_cties <- terra::vect(files$county)
rtp_cty <- rtp_subset(nc_cties)
terra::writeVector(rtp_cty, "../tests/testdata/rtp_counties.shp",
                   overwrite = TRUE)
```

ERA5 subset of 3 days

```{r}
era5 <- data.table::fread(files$era5) %>%
  HeatModel::create_stdtobj(crs_stdt = "EPSG:4326") %>%
  HeatModel::convert_stdt_spatrastdataset()
rtp_era5 <- rtp_subset(era5)

# extract 3 dates
dates <- c("2022-08-01", "2022-08-02", "2022-08-03")
list_era5_var <- list()
for (era5_var in names(rtp_era5)) {
  list_era5_var[[era5_var]] <- rtp_era5[[era5_var]][[dates]]
}
rtp_era5 <- terra::sds(list_era5_var)
plot(rtp_era5[[2]])
rtp_era5_dt <- HeatModel::convert_stobj_to_stdt(rtp_era5)
write.csv(rtp_era5_dt$stdt,  "../tests/testdata/rtp_era5.csv")
```



Empty small SpatVector in RTP area 

```{r}
lon <- seq(-79.18, -78.40, length.out = 5) # create lon sequence
lat <- seq(35.7, 36.10, length.out = 5) # create lat sequence
df <- expand.grid("lon" = lon, "lat" = lat) # expand to regular grid
vector_rtp <- terra::vect(df,
                          geom = c("lon", "lat"),
                          crs = "EPSG:4326",
                          keepgeom = FALSE)
terra::writeVector(vector_rtp, "../tests/testdata/rtp_spatvector.shp",
                   overwrite = TRUE)
```

Small lon-lat-time dataframe

```{r}
lon <- seq(-79.18, -78.40, length.out = 5)
lat <- seq(35.7, 36.10, length.out = 5)
obs <- expand.grid("lon" = lon, "lat" = lat) %>%
  data.table::as.data.table() %>%
  replicate(n = 10, simplify = FALSE) %>%
  data.table::rbindlist()
counties <- rep(c("Wake", "Durham", "Orange", "Camden", "Jackson"), 5)
networks <- c(rep("net1", 5), rep("net2", 5), rep("net3", 5), rep("net4", 5),
              rep("net5", 5))
time_seq <- seq(as.Date("2022-08-01"), as.Date("2022-08-25"), by = "day")
obs$time <- rep(time_seq, 10)
obs$station <- rep(seq(1, 25, 1), 10)
obs$county <- rep(counties, 10)
obs$network <- rep(networks, 10)
write.csv(obs, "../tests/testdata/rtp_points.csv")
```

