---
title: "divide-prediction-grid-per-day"
output: html_document
date: "2023-09-07"
---

```{r, message=F}
library(data.table)
```

Open full prediction grid

```{r}
input_path <- "../input/"
pred <- fread(paste0(input_path,
                     "prediction_grid_points_",
                     "urb_rur_space_time_covariates_jja2022.csv"))
colnames(pred) <- c(
  "geom", "geo", "imp", "tcc", "build.fp",
  "dem", "build.h", "lon", "lat", "date",
  "TNwmo", "TN7am", "TN12am", "TXwmo", "TX7am", "TX12am"
)
```

Create a folder to store all prediction grid per dates

```{r}
if (!dir.exists("../input/prediction-grid")) {
  dir.create("../input/prediction-grid")
}
```

Save each date seperately 

```{r}
dates <- seq(as.Date("2022-06-01"), as.Date("2022-08-31"), by = "1 day")
dates <- as.character(dates)
for (d in dates) {
  file <- pred[date == d, ]
  fwrite(file, paste0(input_path,
                      "prediction-grid/prediction_grid_points",
                      "_urb_rur_space_time_covariates_", d, ".csv"))
}
```

