---
title: "econet-stations-open-add-covariates"
output: html_document
date: "2023-08-25"
---

#### Libraries

```{r, message=FALSE}
library(terra)
library(sf)
library(sftime)

library(ggplot2)
library(ggspatial)
library(tidyterra)
library(rgeos)
library(data.table) # -- for large flat datasets
library(DT)

# -- for timeseries
library(lubridate)
library(xts)

library(purrr)
library(openxlsx)
```

```{r}
input_path <- "../input/"
```


#### Open and merge ECONET excel files

```{r}
files <- list.files(path = "../input/ECONET-stations/", pattern = "M*.xlsx")
files
eco <- do.call("rbind", lapply(files, FUN = function(file) {
  read.xlsx(paste0("../input/ECONET-stations/", file))
}))
```

Reformat the data

```{r}
colnames(eco) <- c("date", "tmax", "tmin", "station", "network", "city",
                   "county", "lat", "lon", "alt", "support")
eco[eco == "QCF"] <- NA
eco$tmax <- as.numeric(eco$tmax)
eco$tmin <- as.numeric(eco$tmin)
eco$date <- as.Date(eco$date, format = "%Y-%m-%d")
eco <- st_as_sftime(eco,
  coords = c("lon", "lat"),
  remove = FALSE,
  crs = "EPSG:4326",
  time_column_name = "date"
)
```

Fahrenheit to Celsius

```{r}
eco$tmin <- (eco$tmin - 32) * 5 / 9
eco$tmax <- (eco$tmax - 32) * 5 / 9
```

#### Map of a single day

```{r}
eco_plot <- eco[which(eco$date == "2022-06-03"), ]
ggplot() +
  geom_point(
    data = eco_plot,
    aes(x = lon, y = lat, color = tmin), size = 2
  ) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "ºC"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()
```

#### Time series

```{r}
ggplot(eco) +
  geom_line(aes(x = date, y = tmin, group = station, color = station)) +
  theme(legend.text = element_blank())

ggplot(eco) +
  geom_point(aes(x = date, y = station, color = is.na(tmin)),
             shape = 15, linewidth = .5) +
  scale_color_manual(values = c("grey", "red")) +
  theme(legend.text = element_blank())

ggplot(eco) +
  geom_point(aes(x = date, y = station, color = is.na(tmax)),
             shape = 15, linewidth = .5) +
  scale_color_manual(values = c("grey", "red")) +
  theme(legend.text = element_blank())

ggplot(eco) +
  geom_point(aes(x = date, y = station, color = tmin),
             shape = 15, linewidth = .5) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "ºC"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  )

ggplot(eco) +
  geom_point(aes(x = date, y = station, color = tmax),
             shape = 15, linewidth = .5) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "ºC"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  )
```

#### Open and add spatial covariates

```{r}
# -- imperviousness
imp_file <- "NC_imperviousness_2019_crs-wgs84.tif"
imp <- rast(paste0(input_path, imp_file))
# -- tree canopy cover
tcc_file <- "NC_tree-canopy-cover_2021_crs-wgs84.tif"
tcc <- rast(paste0(input_path, tcc_file))
# -- building footprint
build_fp_file <- "NC_building-footprints/NorthCarolina_sum_crs-wgs84.tif"
build_fp <- rast(paste0(input_path, build_fp_file))
# -- building height
build_h_file <- paste0("NC_building-height-by-block/",
                       "NC_building-heights-by-block_crs-wgs84.shp")
build_h <- vect(paste0(input_path, build_h_file))
# -- digital elevation model
dem_file <- "NC-DEM_crs-wgs84.tif"
dem <- rast(paste0(input_path, dem_file))
```

Add space covariates

```{r}
eco_spatcov <- unique(eco[, c("station")])
eco_spatcov <- terra::extract(imp, eco_spatcov, bind = TRUE)
eco_spatcov <- terra::extract(tcc, eco_spatcov, fun = "mean",
                              method = "bilinear", bind = TRUE)
eco_spatcov <- terra::extract(build.fp, eco_spatcov, fun = "mean",
                              method = "bilinear", bind = TRUE)
eco_spatcov <- terra::extract(dem, eco_spatcov, bind = TRUE)

# -- build.h is a vector and not a raster, bind=TRUE doesn't work...
stations0 <- terra::extract(build.h[, c("Height_cat")], eco_spatcov)
eco_spatcov$build.h <- stations0$Height_cat
```

#### Open and add time covariates

```{r}
eco_timecov <- unique(eco[, c("station")])

file_era5_tnwmo <- "era5_daily_reanalysis_20220601_20220831_TNwmo.tif"
file_era5_tn7am <- "era5_daily_reanalysis_20220601_20220831_TN7am.tif"
file_era5_tn12am <- "era5_daily_reanalysis_20220601_20220831_TN12am.tif"

era5_tnwmo <- rast(paste0(input_path, file_era5_tnwmo))
era5_tn7am <- rast(paste0(input_path, file_era5_tn7am))
era5_tn12am <- rast(paste0(input_path, file_era5_tn12am))


era5_tnwmo <- project(era5_tnwmo, "EPSG:4326")
era5_tn7am <- project(era5_tn7am, "EPSG:4326")
era5_tn12am <- project(era5_tn12am, "EPSG:4326")

eco_timecov_tnwmo <- terra::extract(era5_tnwmo, eco_timecov, bind = TRUE)
eco_timecov_tn7am <- terra::extract(era5_tn7am, eco_timecov, bind = TRUE)
eco_timecov_tn12am <- terra::extract(era5_tn12am, eco_timecov, bind = TRUE)

file_era5_txwmo <- "era5_daily_reanalysis_20220601_20220831_TXwmo.tif"
file_era5_tx7am <- "era5_daily_reanalysis_20220601_20220831_TX7am.tif"
file_era5_tx12am <- "era5_daily_reanalysis_20220601_20220831_TX12am.tif"

era5_txwmo <- rast(paste0(input_path, file_era5_txwmo))
era5_tx7am <- rast(paste0(input_path, file_era5_tx7am))
era5_tx12am <- rast(paste0(input_path, file_era5_tx12am))

era5_txwmo <- project(era5_txwmo, "EPSG:4326")
era5_tx7am <- project(era5_tx7am, "EPSG:4326")
era5_tx12am <- project(era5_tx12am, "EPSG:4326")

eco_timecov_txwmo <- terra::extract(era5_txwmo, eco_timecov, bind = TRUE)
eco_timecov_tx7am <- terra::extract(era5_tx7am, eco_timecov, bind = TRUE)
eco_timecov_tx12am <- terra::extract(era5_tx12am, eco_timecov, bind = TRUE)

df_eco_timecov_tnwmo <- melt(setDT(as.data.frame(eco_timecov_tnwmo)),
                             id.vars = "station",
                             variable.name = "date",
                             value.name = "TNwmo")
df_eco_timecov_tn7am <- melt(setDT(as.data.frame(eco_timecov_tn7am)),
                             id.vars = "station",
                             variable.name = "date",
                             value.name = "TN7am")
df_eco_timecov_tn12am <- melt(setDT(as.data.frame(eco_timecov_tn12am)),
                              id.vars = "station",
                              variable.name = "date",
                              value.name = "TN12am")
df_eco_timecov_txwmo <- melt(setDT(as.data.frame(eco_timecov_txwmo)),
                             id.vars = "station",
                             variable.name = "date",
                             value.name = "TXwmo")
df_eco_timecov_tx7am <- melt(setDT(as.data.frame(eco_timecov_tx7am)),
                             id.vars = "station",
                             variable.name = "date",
                             value.name = "TX7am")
df_eco_timecov_tx12am <- melt(setDT(as.data.frame(eco_timecov_tx12am)),
                              id.vars = "station",
                              variable.name = "date",
                              value.name = "TX12am")

df <- merge(df_eco_timecov_tnwmo,
            df_eco_timecov_tn7am,
            by = c("station", "date"))
df <- merge(df, df_eco_timecov_tn12am, by = c("station", "date"))
df <- merge(df, df_eco_timecov_txwmo, by = c("station", "date"))
df <- merge(df, df_eco_timecov_tx7am, by = c("station", "date"))
df <- merge(df, df_eco_timecov_tx12am, by = c("station", "date"))
```

Merge all extracted covariates to eco dataframe

```{r}
df$date <- as.Date(as.numeric(df$date), origin = "2022-06-01")
eco$date <- as.Date(eco$date)
eco <- merge(df, eco, by = c("station", "date"))

eco <- merge(eco, eco_spatcov, by = c("station"))
colnames(eco)[which(names(eco) == "NC_imperviousness_2019")] <- "imp"
colnames(eco)[which(names(eco) == "NC_tree-canopy-cover_2021")] <- "tcc"
colnames(eco)[which(names(eco) == "NorthCarolina_sum")] <- "build.fp"
colnames(eco)[which(names(eco) == "Layer_1")] <- "dem"

datatable(eco[, c("station", "tmin", "TNwmo", "tmax", "TXwmo", "dem", "imp",
                  "tcc", "build.fp", "build.h")], filter = "top")
```

#### Save ECONET dataset with covariates

```{r}
fwrite(eco,
       input_path,
       "NC-econet-dailysummary-20220601-20220831-space-time-covariates.csv")
```
