---
title: "map-nc-land-covariates"
output: html_document
date: "2023-07-18"
---

Open covariates file names

```{r}
cfl <- list_covar_testdata(covar_folder = "../tests/testdata/")
rtp_cty <- terra::vect(cfl$county)
```

Create mapping function

```{r}
rtp_map <- function(rast, title, rast_unit) {
  map <- ggplot() +
  tidyterra::geom_spatraster(data = rast) +
  geom_sf(
    data = sf::st_as_sf(rtp_cty), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  tidyterra::scale_fill_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = rast_unit),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE),
    na.value = NA
  ) +
  labs(
    fill = "",
    title = title
  ) +
  ggspatial::annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  ggspatial::annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
  return(map)
}

```

Map covariates

```{r, eval=FALSE}
dem <- terra::rast(cfl$dem)
slope <- terra::terrain(dem, "slope")
aspect <- terra::terrain(dem, "aspect")
roughness <- terra::terrain(dem, "roughness")
flowdir <- terra::terrain(dem, "flowdir")
rtp_map(dem, "Digital Elevation Model", "m")
rtp_map(slope, "Slope", "°")
rtp_map(aspect, "Aspect", "°")
rtp_map(roughness, "Roughness", "m")
rtp_map(flowdir, "Flowdir", "")

tcc <- terra::rast(cfl$tcc)
rtp_map(tcc, "Tree canopy cover", "%") +
  tidyterra::scale_fill_whitebox_c(
    palette = "muted",
    limits = c(0, 100),
    labels = scales::label_number(suffix = "%"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE),
    na.value = NA
  )

canopy_h <- terra::rast(cfl$canopy_h)
rtp_map(canopy_h, "Canopy height", "m")

imp <- terra::rast(cfl$imp)
rtp_map(imp, "Imperviousness", "%")

build_fp <- terra::rast(cfl$build_fp)
rtp_map(build_fp, "Building footprint", "m^2")

build_h <- terra::vect(cfl$build_h)
p_build_h <- ggplot() +
  tidyterra::geom_spatvector(data = build_h,
                             aes(fill = Height_cat),
                             color = NA) +
  geom_sf(
    data = sf::st_as_sf(rtp_cty), aes(geometry = geometry),
    colour = "white", linewidth = .3, fill = NA
  ) +
  scale_fill_manual(
    breaks = c("Low", "Low-medium", "Medium", "Medium-High",
               "High", "Very high"),
    values = c("#38a700", "#d0ff73", "#feebbf", "#ff7f7e",
               "#e60100", "#720000")
  ) +
  labs(
    fill = "",
    title = "Building height by block"
  ) +
  ggspatial::annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  ggspatial::annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
p_build_h

nlcd <- terra::rast(cfl$nlcd)
nlcd_table <- nlcd_table()
val <- split(nlcd_table$col, seq(nrow(nlcd_table)))
val <- setNames(val, nlcd_table$names)
rtp_map(nlcd, "National Land Cover Dataset", "") +
  scale_fill_manual(values = val,
                    labels = nlcd_table$names)
  
```

ERA5 statistic on a specific date

```{r}
era5 <- data.table::fread(cfl$era5) %>%
    HeatModel::create_stdtobj(crs_stdt = "EPSG:4326") %>%
    HeatModel::convert_stdt_spatrastdataset()

rtp_map(era5[["tn12am"]][["2022-08-01"]], "Minimum temperature", "°C") +
  tidyterra::scale_fill_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 6,
    guide = guide_legend(reverse = TRUE),
    na.value = NA
  )

rtp_map(era5[["tx12am"]][["2022-08-01"]], "Maximum temperature", "°C") +
  tidyterra::scale_fill_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 6,
    guide = guide_legend(reverse = TRUE),
    na.value = NA
  )
```

Session info

```{r}
sessionInfo()
```
