---
title: "open-format-wb-height"
output: html_document
date: "2023-08-30"
---

```{r}
library(terra)
library(sf)
library(ggplot2)
library(ggspatial)
library(tidyterra)
library(rgeos)
library(data.table)
library(DT)
library(lubridate)
library(xts)
```


Open raw file of land cover on US 

```{r}
input_path <- "../input/"
nlcd <- rast(paste0(input_path,
                    "/nlcd_2021_land_cover_l48_20230630/",
                    "nlcd_2021_land_cover_l48_20230630.img"))
```

Extract NC borders

```{r}
nc_poly <- paste0("NC_county_boundary/",
                  "North_Carolina_State_and_County_Boundary_Polygons.shp")
nc_borders <- vect(paste0(input_path, nc_poly))
nc_borders <- project(nc_borders, crs(nlcd))
nc_nlcd <- terra::crop(nlcd, nc_borders)
```

Plot nc_nlcd


```{r}
plot(nc_nlcd)
plot(nc_borders, add = TRUE)
```


Project on crs_proj

```{r}
crs_proj <- "EPSG:5070"
nc_nlcd_proj <- project(nc_nlcd, crs_proj)
```

Save all final files

```{r}
writeRaster(nc_nlcd,
            filename = paste0(input_path, "NC_nlcd_crs-wgs84.tif"),
            overwrite = TRUE)
writeRaster(nc_nlcd_proj,
            filename = paste0("../input/NC_nlcd_crs-albers.tif"),
            overwrite = TRUE)
```
