---
title: "process_era5_reanalysis"
output: html_document
date: "2023-10-26"
---

```{r, message=F}
library(DT)
source("../R/process_era5_temperature_reanalysis.R")
```

Open era5, compute tn and tx and store daily dataframe

```{r}
era5 <- convert_era5nc_to_dt()
era5_tn <- compute_tn(era5)
era5_tx <- compute_tx(era5)
era5_daily <- merge(era5_tn,
  era5_tx,
  by = c("geom", "date", "lon", "lat")
)
```

```{r}
fwrite(
  era5_daily,
  paste0(
    "../input/era5_daily_reanalysis_",
    min(era5_daily$date),
    "_",
    max(era5_daily$date),
    ".csv"
  )
)
```

Convert to SpatRasterDataset

```{r}
head(era5_daily)
era5_daily <- era5_daily %>% rename("time" = "date")
source("../R/manipulate_spacetime_data.R")
stdt_obj <- create_stdtobj(era5_daily, "EPSG:4326")
sprastds <- convert_stdt_spatrastdataset(stdt_obj)
```

```{r}
# map
image(sprastds["TNwmo"]$`2022-06-14`)
image(sprastds["TNwmo"]$`2022-06-15`)
image(sprastds["TNwmo"]$`2022-06-16`)

# time serie
one_pixel <- sprastds["TNwmo"][1, 1]
dates <- as.Date(colnames(one_pixel))
plot(dates, one_pixel)
```
