---
title: "kriging"
output: html_document
date: "2023-08-29"
---

Libraries

```{r, message=FALSE}
pkgs <- c(
  "terra",
  "exactextractr",
  "tidyverse",
  "tidyterra",
  "data.table",
  "sf",
  "xts",
  "ggplot2",
  "ggspatial",
  "lubridate"
)
sapply(pkgs, library, character.only = TRUE)
```

#### Open data

```{r}
file <- "NC-monitors-dailysummary-20220601-20220831-space-time-covariates.csv"
obs <- fread(paste0("../input/", file))
nc_poly_file <- "North_Carolina_State_and_County_Boundary_Polygons.shp"
nc_borders <- vect(paste0("../input/NC_county_boundary/", nc_poly_file))
```

Specific date

```{r}
d <- "2022-06-02"
outcome <- "tmin"
pred_file <- paste0("prediction_grid_points_urb_rur_space_time_covariates_",
                    d, ".csv")
pred_d <- fread(paste0("../input/prediction-grid/", pred_file))
obs_d <- obs[date == d, ]
```

Choose a projection in meters

```{r}
obs_d <- st_as_sf(obs_d,
  coords = c("lon", "lat"),
  remove = FALSE,
  crs = "EPSG:4326"
)
pred_d <- st_as_sf(pred_d,
  coords = c("lon", "lat"),
  remove = FALSE,
  crs = "EPSG:4326"
)

nc_borders <- project(nc_borders, "EPSG:5070")
obs_d <- st_transform(obs_d, "EPSG:5070")
pred_d <- st_transform(pred_d, "EPSG:5070")
```

Remove NA in obs_d

```{r}
obs_d <- obs_d[!is.na(obs_d$tmin) & !is.na(obs_d$tmax), ]
```

#### Variogram analysis

Directions: 0=north, 90=east, 180=south, 270=west

```{r}
cutoff <- 30000
width <- 1000
plot(variogram(tmin ~ 1, obs_d, cloud = TRUE, cutoff = cutoff, width = width),
     main = "semivariogram cloud")
plot(variogram(tmin ~ 1, obs_d, cutoff = cutoff, width = width),
     main = "sample semivariogram")
plot(variogram(tmin ~ 1, obs_d, cutoff = cutoff, width = width,
               alpha = c(0, 45, 90, 135, 180, 225, 270, 315)),
     main = "direction dependance")
```

Variogram model

```{r}
cutoff <- 100000
v_emp <- variogram(tmin ~ 1, obs_d, cutoff = cutoff, width = width)

nugget <- 0.5
range <- 20000
vgm_sph <- vgm(psill = 3, "Sph", range = range, nugget = 0.5, cutoff = cutoff)
plot(v_emp, vgm_sph, cutoff = cutoff)

vgm_exp <- vgm(psill = 3, "Exp", range = range, nugget = 0.5, cutoff = cutoff)
plot(v_emp, vgm_exp, cutoff = cutoff)

vgm_mat <- vgm(psill = 3, "Mat", range = range, nugget = 0.5, cutoff = cutoff)
plot(v_emp, vgm_mat, cutoff = cutoff)
```

Fit Matern model

```{r}
v_fit <- fit.variogram(v_emp, vgm_mat, fit.range = FALSE)
plot(v_emp, v_fit)
```

## Spatial kriging

#### Ordinary kriging

```{r}
cutoff <- 100000
nugget <- 0.5
range <- 20000
width <- 1000
v_emp <- variogram(tmin ~ 1, obs_d, cutoff = cutoff, width = width)
vgm_mat <- vgm(psill = 3, "Mat", range = range, nugget = nugget,
               cutoff = cutoff)
v_fit <- fit.variogram(v_emp, vgm_mat, fit.range = FALSE)
ok <- gstat::krige(tmin ~ 1, obs_d, newdata = pred_d, v_fit)
```

```{r}
m <- ggplot() +
  geom_spatvector(data = vect(ok), aes(color = var1.pred), size = .1) +
  geom_sf(data = obs_d, aes(geometry = geometry, color = tmin)) +
  geom_sf(
    data = st_as_sf(nc_borders), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  labs(
    fill = "",
    title = "Ordinary kriging"
  ) +
  annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
m
```

#### Universal kriging

```{r}
cutoff <- 100000
nugget <- 0.5
range <- 20000
width <- 1000
v_emp <- variogram(tmin ~ dem + imp + TN12am + tcc + build.fp,
                   obs_d, cutoff = cutoff, width = width)
vgm_mat <- vgm(psill = 2, "Mat", range = range, nugget = nugget,
               cutoff = cutoff)
plot(v_emp, vgm_mat)
```

```{r}
v_fit <- fit.variogram(v_emp, vgm_mat, fit.range = FALSE)
plot(v_emp, v_fit)
uk <- gstat::krige(tmin ~ dem + imp + TN12am + tcc + build.fp, obs_d,
                   newdata = pred_d, v_fit)
```

```{r}
m <- ggplot() +
  geom_spatvector(data = vect(uk), aes(color = var1.pred), size = .1) +
  geom_sf(data = obs_d, aes(geometry = geometry, color = tmin)) +
  geom_sf(
    data = st_as_sf(nc_borders), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  labs(
    fill = "",
    title = "Universal kriging"
  ) +
  annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
m
```

Same without ERA5

```{r}
cutoff <- 100000
nugget <- 0.5
range <- 20000
width <- 1000
v_emp <- variogram(tmin ~ dem + imp + tcc + build.fp, obs_d, cutoff = cutoff,
                   width = width)
vgm_mat <- vgm(psill = 3, "Mat", range = range, nugget = nugget,
               cutoff = cutoff)
plot(v_emp, vgm_mat)
v_fit <- fit.variogram(v_emp, vgm_mat, fit.range = FALSE, fit.sill = FALSE)
plot(v_emp, v_fit)
uk <- gstat::krige(tmin ~ dem + imp + tcc + build.fp, obs_d,
                   newdata = pred_d, v_fit)
```

```{r}
plot_uk_noera5 <- ggplot() +
  geom_spatvector(data = vect(uk), aes(color = var1.pred), size = .1) +
  geom_sf(data = obs_d, aes(geometry = geometry, color = tmin)) +
  geom_sf(
    data = st_as_sf(nc_borders), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  labs(
    fill = "",
    title = "Universal kriging"
  ) +
  annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
plot_uk_noera5
```

Zoom on RTP area

```{r}
lat <- c(35.6, 36.11, 36.11, 35.6)
lon <- c(-79.19, -79.10, -78.39, -78.39)
ext_rtp <- vect(cbind(lon, lat), type = "points", crs = "EPSG:4326")
ext_rtp <- project(ext_rtp, "EPSG:5070")
ext(ext_rtp)
```

```{r}
uk_rtp <- crop(vect(uk), ext_rtp)
imp_rtp <- crop(vect(pred_d[, "imp"]), ext_rtp)
obs_rtp <- crop(vect(obs_d), ext_rtp)

ggplot() +
  geom_spatvector(data = uk_rtp, aes(color = var1.pred), size = .1) +
  geom_spatvector(data = obs_rtp, aes(color = tmin), shape = 1, size = 2) +
  # geom_sf(data = st_as_sf(nc_borders), aes(geometry=geometry),
  #             colour = "grey", linewidth=.3, fill = NA) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  labs(
    fill = "",
    title = "Universal kriging RTP"
  ) +
  annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )

ggplot() +
  geom_spatvector(data = imp_rtp, aes(color = imp), size = .1) +
  geom_spatvector(data = obs_rtp, color = "black", fill = "black",
                  shape = 16, size = 2) +
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "%"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  labs(
    fill = "",
    title = "Imperviousness RTP"
  ) +
  annotation_scale(
    location = "bl", pad_x = unit(1, "cm"),
    pad_y = unit(1, "cm"),
    height = unit(0.30, "cm"),
    text_cex = 1
  ) +
  annotation_north_arrow(
    location = "br",
    which_north = "true",
    pad_x = unit(0.2, "cm"),
    pad_y = unit(0.2, "cm")
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
```

10-fold cross validation

```{r}
uk_loocv <- krige.cv(tmin ~ dem + imp + tcc + build.fp, obs_d, v_fit,
                     nfold = nrow(obs_d))
uk_loocv
uk_10cv <- krige.cv(tmin ~ dem + imp + tcc + build.fp, obs_d, v_fit, nfold = 10)
uk_10cv
```

RMSE computation

```{r}
rmse_loocv <- sqrt(sum(uk_loocv$residual**2) / nrow(uk_loocv))
rmse_10cv <- sqrt(sum(uk_10cv$residual**2) / nrow(uk_10cv))
cat("RMSE with loocv:", rmse_loocv, "°C\n")
cat("RMSE with 10cv: ", rmse_10cv, "°C")
```

Residuals

```{r}
ggplot(uk_loocv) +
  geom_point(aes(y = var1.pred, x = observed)) +
  geom_abline(aes(slope = 1, intercept = 0), color = "red")

ggplot(uk_10cv) +
  geom_point(aes(y = var1.pred, x = observed)) +
  geom_abline(aes(slope = 1, intercept = 0), color = "red")

ggplot() +
  geom_sf(data = uk_loocv, aes(geometry = geometry, color = residual)) +
  geom_sf(
    data = st_as_sf(nc_borders), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  scale_color_steps2(low = "blue", mid = "white", high = "red",
                     limits = c(-5, 5), n.breaks = 10) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )

ggplot() +
  geom_sf(data = uk_10cv, aes(geometry = geometry, color = residual)) +
  geom_sf(
    data = st_as_sf(nc_borders), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  scale_color_steps2(low = "blue", mid = "white", high = "red",
                     limits = c(-5, 5), n.breaks = 10) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
```

```{r}
head(uk_loocv)
ggplot() +
  geom_sf(data = uk_10cv, aes(geometry = geometry, color = fold)) +
  geom_sf(
    data = st_as_sf(nc_borders), aes(geometry = geometry),
    colour = "grey", linewidth = .3, fill = NA
  ) +
  theme(
    axis.text = element_text(size = 12, family = "serif"),
    plot.caption = element_text(size = 10, family = "serif"),
    legend.text = element_text(size = 12, family = "serif"),
    legend.title = element_text(size = 12, family = "serif"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(colour = "grey")
  )
```
