---
title: "create-prediction-grid"
output:
  pdf_document: default
  html_document: default
date: "2023-07-20"
---

Libraries

```{r, results='hide'}
#library(raster)   # -- old
#library(sp)       # -- old
#library(rgdal)    # -- deprecated in 10/2023
#library(rgeos)    # -- deprecated in 10/2023
#library(maptools) # -- deprecated in 10/2023
library(terra)
library(sf)

library(ggplot2)
library(rgeos)
```

```{r}
nc.borders <- vect("../input/NC_county_boundary/North_Carolina_State_and_County_Boundary_Polygons.shp")
```

```{r eval=FALSE}
#beepr::beep(sound=6)
```

Change nc.borders units (us feet to meter)

```{r}
crs.meters <- "+proj=lcc +lat_0=33.75 +lon_0=-79 +lat_1=36.1666666666667 +lat_2=34.3333333333333 +x_0=609601.219202439 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
nc.borders <- project(nc.borders, crs.meters)
```

Create a 500m-resolution raster in NC shapefile

```{r}
grid <- rast(ext(nc.borders), resolution = c(10000, 10000), crs = crs.meters)
grid <- extend(grid, c(1,1))
gridPolygon <- as.polygons(grid)
final.grid <- intersect(gridPolygon, nc.borders)
writeVector(final.grid, filename="../input/prediction.grid.empty.shp", overwrite=T)
```

Map with r base plot function

```{r, eval=F}
plot(nc.borders)
plot(final.grid, add=T)
```

Session info

```{r}
sessionInfo()
```
