---
title: "spatiotemporal-variography"
output:
  pdf_document: default
  html_document: default
date: "2023-08-23"
---

Libraries

```{r, message=F}
#library(raster)   # -- old
#library(sp)       # -- old
#library(rgdal)    # -- deprecated in 10/2023
#library(rgeos)    # -- deprecated in 10/2023
#library(maptools) # -- deprecated in 10/2023
library(terra)
library(sf)

library(ggplot2)
library(ggspatial)
library(tidyterra)
library(rgeos)
library(data.table) # -- for large flat datasets

# space-time variography
library(gstat)
```

## Open observations

```{r}
aws <- fread("../input/NC-AWS-NOAA-dailysummary-20220601-20220831-space-time-covariates.csv")
```

#### Plot TMIN for each month

```{r}
ggplot(aws[between(DATE, as.Date('2022-05-31'), as.Date('2022-06-30'))])+
  geom_point(aes(x=LONGITUDE, y=LATITUDE, color=TMIN))+
  facet_wrap(~DATE)+
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()

ggsave("../output/noaa_obs_202206_TMIN.png", width=15, height=5, dpi=300)

ggplot(aws[between(DATE, as.Date('2022-07-01'), as.Date('2022-07-31'))])+
  geom_point(aes(x=LONGITUDE, y=LATITUDE, color=TMIN))+
  facet_wrap(~DATE)+
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()

ggsave("../output/noaa_obs_202207_TMIN.png", width=15, height=6, dpi=300)

ggplot(aws[between(DATE, as.Date('2022-08-01'), as.Date('2022-08-31'))])+
  geom_point(aes(x=LONGITUDE, y=LATITUDE, color=TMIN))+
  facet_wrap(~DATE)+
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()

ggsave("../output/noaa_obs_202208_TMIN.png", width=15, height=6, dpi=300)
```

#### Plot TMAX for each month

```{r}
ggplot(aws[between(DATE, as.Date('2022-05-31'), as.Date('2022-06-30'))])+
  geom_point(aes(x=LONGITUDE, y=LATITUDE, color=TMAX))+
  facet_wrap(~DATE)+
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()

ggsave("../output/noaa_obs_202206_TMAX.png", width=15, height=5, dpi=300)

ggplot(aws[between(DATE, as.Date('2022-07-01'), as.Date('2022-07-31'))])+
  geom_point(aes(x=LONGITUDE, y=LATITUDE, color=TMAX))+
  facet_wrap(~DATE)+
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()

ggsave("../output/noaa_obs_202207_TMAX.png", width=15, height=6, dpi=300)

ggplot(aws[between(DATE, as.Date('2022-08-01'), as.Date('2022-08-31'))])+
  geom_point(aes(x=LONGITUDE, y=LATITUDE, color=TMAX))+
  facet_wrap(~DATE)+
  scale_color_whitebox_c(
    palette = "muted",
    labels = scales::label_number(suffix = "°C"),
    n.breaks = 12,
    guide = guide_legend(reverse = TRUE)
  ) +
  coord_equal()

ggsave("../output/noaa_obs_202208_TMAX.png", width=15, height=6, dpi=300)
```

```{r}
ggplot(aws) +
  	geom_tile(aes(x = as.factor(LONGITUDE), y = DATE, fill = TMIN)) +
		scale_y_date(date_labels="%d/%m", date_breaks='7 days', 
		  date_minor_breaks='1 day', 
			limits=c(as.Date("2022-06-01", tz="UTC"), as.Date("2022-08-31", tz="UTC")))+
    scale_fill_whitebox_c(
      palette = "muted",
      labels = scales::label_number(suffix = "°C"),
      n.breaks = 12,
      guide = guide_legend(reverse = TRUE)
  ) +
    ggtitle('TMIN')+
		#guides(fill = guide_colourbar(barwidth = 1.5, barheight=22))+
  	theme(axis.text.x = element_blank(),
			      axis.text.y = element_text(size=16),
		      	axis.title.x = element_text(size=22), 
		      	axis.title.y = element_text(size=22),
        		legend.key.width = unit(1, 'cm'), 
        		panel.grid.major = element_line(color="grey", size=0.2),
        		legend.text = element_text(size=16),
        		plot.caption = element_text(size=14),
        		legend.title = element_text(size=18),
        		legend.text.align = 0,
        		legend.box.spacing=unit(0, "pt"))

ggplot(aws) +
  	geom_tile(aes(x = as.factor(LONGITUDE), y = DATE, fill = TMAX)) +
		scale_y_date(date_labels="%d/%m", date_breaks='7 days', 
		             date_minor_breaks='1 day', 
		             limits=c(as.Date("2022-06-01", tz="UTC"), as.Date("2022-08-31", tz="UTC")))+
    scale_fill_whitebox_c(
      palette = "muted",
      labels = scales::label_number(suffix = "°C"),
      n.breaks = 12,
      guide = guide_legend(reverse = TRUE)
  ) +
    ggtitle('TMAX')+
		#guides(fill = guide_colourbar(barwidth = 1.5, barheight=22))+
  		theme(axis.text.x = element_blank(),
			      axis.text.y = element_text(size=16),
		      	axis.title.x = element_text(size=22), 
		      	axis.title.y = element_text(size=22),
        		legend.key.width = unit(1, 'cm'), 
        		panel.grid.major = element_line(color="grey", size=0.2),
        		legend.text = element_text(size=16),
        		plot.caption = element_text(size=14),
        		legend.title = element_text(size=18),
        		legend.text.align = 0,
        		legend.box.spacing=unit(0, "pt"))

```

TMIN and TMAX according to covariates

```{r}
ggplot(aws)+ 
  geom_point(aes(x=LONGITUDE, y=TMIN), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=LATITUDE, y=TMIN), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=dem, y=TMIN), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=tcc, y=TMIN), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=build.fp, y=TMIN), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=imp, y=TMIN), alpha=.2)

ggplot(aws)+ 
  geom_boxplot(aes(group=build.h, x=build.h, y=TMIN))
```

```{r}
ggplot(aws)+ 
  geom_point(aes(x=LONGITUDE, y=TMAX), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=LATITUDE, y=TMAX), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=dem, y=TMAX), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=tcc, y=TMAX), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=build.fp, y=TMAX), alpha=.2)

ggplot(aws)+ 
  geom_point(aes(x=imp, y=TMAX), alpha=.2)

ggplot(aws)+ 
  geom_boxplot(aes(group=build.h, x=build.h, y=TMAX))
```

```{r}
summary.jja <- aws[, .(TMIN.mean=mean(TMIN), 
                       TMAX.mean=mean(TMAX), 
                       TMIN.min=min(TMIN), 
                       TMAX.min=min(TMAX), 
                       TMIN.max=max(TMIN), 
                       TMAX.max=max(TMAX)), keyby=c('DATE')]

```

```{r}
ggplot()+
  geom_line(data=aws, aes(y=TMIN, x=DATE, group=STATION),color='navyblue', alpha=0.1)+
  geom_line(data=summary.jja, aes(y=TMIN.mean, x=DATE),color='black', alpha=1, linewidth=.7)+
  geom_line(data=summary.jja, aes(y=TMIN.min, x=DATE),color='black', alpha=1, linewidth=.7, linetype='dashed'
)+
  geom_hline(yintercept=20, color='orange')+
  geom_line(data=summary.jja, aes(y=TMIN.max, x=DATE),color='black', alpha=1, linewidth=.7, linetype='dashed')+
  theme_minimal()
ggsave("../output/noaa_obs_jja_timeseries_TMIN.png", width=15, height=5, dpi=300)

ggplot()+
  geom_line(data=aws, aes(y=TMAX, x=DATE, group=STATION),color='red', alpha=0.1)+
  geom_line(data=summary.jja, aes(y=TMAX.mean, x=DATE),color='black', alpha=1, linewidth=.7)+
  geom_line(data=summary.jja, aes(y=TMAX.min, x=DATE),color='black', alpha=1, linewidth=.7, linetype='dashed')+
  geom_hline(yintercept=35, color='orange')+
  geom_line(data=summary.jja, aes(y=TMAX.max, x=DATE),color='black', alpha=1, linewidth=.7, linetype='dashed')+
  theme_minimal()
ggsave("../output/noaa_obs_jja_timeseries_TMAX.png", width=15, height=5, dpi=300)
```

#### Space-time covariography

```{r}
metricVgm <- vgmST("separable", 
                   space=vgm(0.9,"Exp", 123, 0.1),
                   time==vgm(0.9,"Exp", 2.9, 0.1), 
                   sill=100)
metricVgm <- fit.StVariogram(vv, metricVgm)
```
