---
title: "open-format-wb-height"
output: html_document
date: "2023-08-30"
---

```{r}
library(terra)
library(sf)

library(ggplot2)
library(ggspatial)
library(tidyterra)
library(rgeos)
library(data.table) # -- for large flat datasets
library(DT)

# -- for timeseries
library(lubridate)
library(xts)
```


Open raw file of land cover on US 

```{r}
nlcd <- rast('../input/nlcd_2021_land_cover_l48_20230630/nlcd_2021_land_cover_l48_20230630.img')
```

Extract NC borders

```{r}
nc.borders <- vect("../input/NC_county_boundary/North_Carolina_State_and_County_Boundary_Polygons.shp") 
nc.borders <- project(nc.borders, crs(nlcd))
nc.nlcd <- terra::crop(nlcd, nc.borders)
```

Plot nc.nlcd


```{r}
plot(nc.nlcd)
plot(nc.borders, add=T)
```


Project on crs.meters

```{r}
crs.meters <- "+proj=lcc +lat_0=33.75 +lon_0=-79 +lat_1=36.1666666666667 +lat_2=34.3333333333333 +x_0=609601.219202439 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
nc.nlcd.meters <- project(nc.nlcd, crs.meters)
```

Save all final files

```{r}
writeRaster(nc.nlcd, filename="../input/NC_nlcd_crs-wgs84.tif", overwrite=T)
writeRaster(nc.nlcd.meters, filename=paste0("../input/NC_nlcd_crs-meters.tif"), overwrite=T)
```